"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.SCOPE_VALUE_NOT_EXIST = exports.EVAL_FUNCTION_IDENTIFIER = exports.DEFAULT_INTERPRETER_MODE = exports.DEFAULT_ECMA_VERSION = void 0;
var DEFAULT_ECMA_VERSION = 2021;
exports.DEFAULT_ECMA_VERSION = DEFAULT_ECMA_VERSION;
var DEFAULT_INTERPRETER_MODE = 'full';
exports.DEFAULT_INTERPRETER_MODE = DEFAULT_INTERPRETER_MODE;
var SCOPE_VALUE_NOT_EXIST = 'SCOPE_VALUE_NOT_EXIST';
exports.SCOPE_VALUE_NOT_EXIST = SCOPE_VALUE_NOT_EXIST;
var EVAL_FUNCTION_IDENTIFIER = 'EVAL_FUNCTION_IDENTIFIER';
exports.EVAL_FUNCTION_IDENTIFIER = EVAL_FUNCTION_IDENTIFIER;