export var DEFAULT_ECMA_VERSION = 2021;
export var DEFAULT_INTERPRETER_MODE = 'full';
export var SCOPE_VALUE_NOT_EXIST = 'SCOPE_VALUE_NOT_EXIST';
export var EVAL_FUNCTION_IDENTIFIER = 'EVAL_FUNCTION_IDENTIFIER';